.\" Manpage for dumpbom.
.\" Contact bomutils@gmail.com
.TH man 1 "28 July 2013" "1.0" "dumpbom man page"
.SH NAME
dumpbom \- list the internal variables and contents of a bill-of-materials fils
.SH SYNOPSIS
dumpbom bom-file
.SH DESCRIPTION
.PP
dumpbom lists the internal variables, sections and blocks of the bill-of-materials file specified with 'bom-file'. This is useful for debugging.
.SH SEE ALSO
mkbom(1), lsbom(1), ls4mkbom(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Fabian Renn (fabian.renn@gmail.com)
http://hogliux.github.io/bomutils
