.\" Manpage for mkbom.
.\" Contact bomutils@gmail.com
.TH man 1 "28 July 2013" "1.0" "mkbom man page"
.SH NAME
mkbom \- create a bill-of-materials file
.SH SYNOPSIS
mkbom [-i] source target-bom-file
.SH DESCRIPTION
.PP
mkbom creates a bill-of-materials file specified by 'target-bom-file' from the contents of the directory specified with 'source'. This bill-of-materials file can be used to create Mac OS X installer packages. Alternatively, by specifying the '-i' option, mkbom can create a bill-of-materials file from a text file specified by source, which lists the contents of a directory in the same format as the output from 'lsbom' and 'ls4mkbom'.
.TP
\fB\-i\fR
create a bill-of-materials file from the text file specified with 'source' which contains a list of files in the same format as the output from 'lsbom' and 'ls4mkbom'. This option is highly recommended when using mkbom on foreign OSes (linux, windows, ...) because it allows the user to modify user and group ids of a directory listing before processing with mkbom.
.SH SEE ALSO
lsbom(1), ls4mkbom(1), dumpbom(1)
.SH BUGS
Symbolic links are not supported
.PP
Long paths and some characters in filenames will cause mkbom to fail on Windows.
.SH AUTHOR
Fabian Renn (bomutils@gmail.com)
http://bomutils.github.io/
